# Name of your blog (this will show up at the top of your page and in the RSS feed)
name: Team AWESOME!

# Short description (goes below the title; it will also be used in the RSS feed)
description: AWESOME!!!!!!!

# Your name, as you want it to appear underneath each post and in the footer
author: ID-10T

# Logo image
logo: ./static/images/logos/strathseds-200px.png

# Your email if you want it to be linked on the contact page
contact_email: rjb12180@uni.strath.ac.uk
web_email: rjb12180@uni.strath.ac.uk

# Committee data
committee_positions: [designer, writer1, writer2, beer, supervisor]
committee:
  designer:
    name: Adam McGhie
    gravatar: 29e309f15dc5748a962f13185d90bf62
    email: rjb12180@uni.strath.ac.uk
    position: Writer of Copyright & Lead Website Designer
    image: default.jpg
  writer1:
    name: Tom Maxwell<!-- Tom by day. Tammy by night -->
    gravatar: 29e309f15dc5748a962f13185d90bf62
    email: gvb12182@uni.strath.ac.uk
    position: Writer of Professional Issues 
    image: tom.jpg
  writer2:
    name: Thomas Sinclair
    gravatar: 29e309f15dc5748a962f13185d90bf62
    email: mlb12174@uni.strath.ac.uk
    position: Writer of Data Protection 
    image: thomas.jpg
  beer:
    name: Grant Toghill
    gravatar: 29e309f15dc5748a962f13185d90bf62
    email: wsb12157@uni.strath.ac.uk
    position: Writer of Role of Computer Scientists & Try Hard Dictator
    image: grant.jpg
  supervisor:
    name: Darren Tang
    gravatar: 29e309f15dc5748a962f13185d90bf62
    email: pjb12147@uni.strath.ac.uk
    position: Writer of Computer Law
    image: darren.jpg

# The URL of your actual domain. This will be used to make absolute links in the RSS feed.
baseurl: .
url: ./

# Static URL's
staticurl: ./static
imageurl: ./static/images/

# Google analytics id
analyticsID: UA-45927086-1
analyticsDomain: digitalwizardry.org

# Misc
future: false

#### Under the Hood Stuff #####

# Use rdiscount as the markdown engine because it generates html5 compliant code for stuff like footnotes
# If you use maroku (default engine) some of your generated pages may not validate or lint as html5
# If you don't have it install it via gem install rdiscount
markdown: rdiscount

# Continue compiling even if there are errors. Keep it true, unless troubleshooting.
auto: true

# Makes pretty (descriptive) permalinks. See Jekyll docs for alternatives.
permalink: :title.html

# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: README.md, package.json, grunt.js, Gruntfile.js, node_modules
